### ISSUE TITLE
@ bind error

### ISSUE THREAD

**Issue by sseworld** [clerk/javascript#2950]
### Preliminary Checks

- [X] I have reviewed the documentation: [https://clerk.com/docs](https://clerk.com/docs)
- [X] I have searched for existing issues: [https://github.com/clerk/javascript/issues](https://github.com/clerk/javascript/issues)
- [X] I have not already reached out to Clerk support via email or Discord (if you have, no need to open an issue here)
- [X] This issue is not a question, general help request, or anything other than a bug report directly related to Clerk. Please ask questions in our Discord community: [https://clerk.com/discord](https://clerk.com/discord).

### Reproduction / Replay Link

[https://github.com/sseworld/sse_form_designer](https://github.com/sseworld/sse_form_designer)

### Publishable key

pk_test_ZWFnZXItdG91Y2FuLTY0LmNsZXJrLmFjY291bnRzLmRldiQ

### Description

**Steps to reproduce:**

1. Step 1
2. Step 2

**Expected behavior:**

**Actual behavior:**

```shell
⨯ node_modules\@clerk\backend\dist\esm\index.js (178:24) @ bind
 ⨯ TypeError: Cannot read properties of undefined (reading 'bind')
    at __webpack_require__ (D:\react\next\sse_yt_pag\.next\server\webpack-runtime.js:33:42)
    at __webpack_require__ (D:\react\next\sse_yt_pag\.next\server\webpack-runtime.js:33:42)
    at __webpack_require__ (D:\react\next\sse_yt_pag\.next\server\webpack-runtime.js:33:42)
    at __webpack_require__ (D:\react\next\sse_yt_pag\.next\server\webpack-runtime.js:33:42)
    at __webpack_require__ (D:\react\next\sse_yt_pag\.next\server\webpack-runtime.js:33:42)
    at eval (./app/layout.tsx:12:71)
    at (rsc)/./app/layout.tsx (D:\react\next\sse_yt_pag\.next\server\app\(dashboard)\page.js:655:1)
    at Function.__webpack_require__ (D:\react\next\sse_yt_pag\.next\server\webpack-runtime.js:33:42)
digest: "1356143276"
null
 ⨯ node_modules\@clerk\backend\dist\esm\index.js (178:24) @ bind
 ⨯ TypeError: Cannot read properties of undefined (reading 'bind')
    at __webpack_require__ (D:\react\next\sse_yt_pag\.next\server\webpack-runtime.js:33:42)
    at __webpack_require__ (D:\react\next\sse_yt_pag\.next\server\webpack-runtime.js:33:42)
    at __webpack_require__ (D:\react\next\sse_yt_pag\.next\server\webpack-runtime.js:33:42)
    at __webpack_require__ (D:\react\next\sse_yt_pag\.next\server\webpack-runtime.js:33:42)
    at __webpack_require__ (D:\react\next\sse_yt_pag\.next\server\webpack-runtime.js:33:42)
    at eval (./app/layout.tsx:12:71)
    at (rsc)/./app/layout.tsx (D:\react\next\sse_yt_pag\.next\server\app\(dashboard)\page.js:655:1)
    at Function.__webpack_require__ (D:\react\next\sse_yt_pag\.next\server\webpack-runtime.js:33:42)
null
TypeError: Cannot read properties of undefined (reading 'bind')
    at eval (webpack-internal:///(rsc)/./node_modules/@clerk/backend/dist/esm/index.js:216:25)
    at (rsc)/./node_modules/@clerk/backend/dist/esm/index.js (D:\react\next\sse_yt_pag\.next\server\vendor-chunks\@clerk.js:569:1)
    at __webpack_require__ (D:\react\next\sse_yt_pag\.next\server\webpack-runtime.js:33:42)
    at eval (webpack-internal:///(rsc)/./node_modules/@clerk/nextjs/dist/esm/server/getAuth.js:7:72)
    at (rsc)/./node_modules/@clerk/nextjs/dist/esm/server/getAuth.js (D:\react\next\sse_yt_pag\.next\server\vendor-chunks\@clerk.js:962:1)
    at __webpack_require__ (D:\react\next\sse_yt_pag\.next\server\webpack-runtime.js:33:42)
    at eval (webpack-internal:///(rsc)/./node_modules/@clerk/nextjs/dist/esm/app-router/server/auth.js:7:73)
    at (rsc)/./node_modules/@clerk/nextjs/dist/esm/app-router/server/auth.js (D:\react\next\sse_yt_pag\.next\server\vendor-chunks\@clerk.js:640:1)
    at __webpack_require__ (D:\react\next\sse_yt_pag\.next\server\webpack-runtime.js:33:42)
    at eval (webpack-internal:///(rsc)/./node_modules/@clerk/nextjs/dist/esm/app-router/server/ClerkProvider.js:9:63)
    at (rsc)/./node_modules/@clerk/nextjs/dist/esm/app-router/server/ClerkProvider.js (D:\react\next\sse_yt_pag\.next\server\vendor-chunks\@clerk.js:629:1)
    at __webpack_require__ (D:\react\next\sse_yt_pag\.next\server\webpack-runtime.js:33:42)
    at eval (webpack-internal:///(rsc)/./node_modules/@clerk/nextjs/dist/esm/index.js:58:69)
    at (rsc)/./node_modules/@clerk/nextjs/dist/esm/index.js (D:\react\next\sse_yt_pag\.next\server\vendor-chunks\@clerk.js:896:1)
    at __webpack_require__ (D:\react\next\sse_yt_pag\.next\server\webpack-runtime.js:33:42)
    at eval (webpack-internal:///(rsc)/./app/layout.tsx:12:71)
    at (rsc)/./app/layout.tsx (D:\react\next\sse_yt_pag\.next\server\app\(dashboard)\page.js:655:1)
    at Function.__webpack_require__ (D:\react\next\sse_yt_pag\.next\server\webpack-runtime.js:33:42)
    at runNextTicks (node:internal/process/task_queues:60:5)
    at listOnTimeout (node:internal/timers:540:9)
    at process.processTimers (node:internal/timers:514:7)
    at async eq (D:\react\next\sse_yt_pag\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:402221)
    at async tr (D:\react\next\sse_yt_pag\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:405987)
    at async tn (D:\react\next\sse_yt_pag\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:406537)
    at async tu (D:\react\next\sse_yt_pag\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:36:2057)
    at async D:\react\next\sse_yt_pag\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:36:2564 {
  digest: '1289085325'
}
 ⨯ node_modules\@clerk\backend\dist\esm\index.js (178:24) @ bind
 ⨯ TypeError: Cannot read properties of undefined (reading 'bind')
    at eval (webpack-internal:///(rsc)/./node_modules/@clerk/backend/dist/esm/index.js:216:25)
    at (rsc)/./node_modules/@clerk/backend/dist/esm/index.js (D:\react\next\sse_yt_pag\.next\server\vendor-chunks\@clerk.js:569:1)
    at __webpack_require__ (D:\react\next\sse_yt_pag\.next\server\webpack-runtime.js:33:42)
    at eval (webpack-internal:///(rsc)/./node_modules/@clerk/nextjs/dist/esm/server/getAuth.js:7:72)
    at (rsc)/./node_modules/@clerk/nextjs/dist/esm/server/getAuth.js (D:\react\next\sse_yt_pag\.next\server\vendor-chunks\@clerk.js:962:1)
    at __webpack_require__ (D:\react\next\sse_yt_pag\.next\server\webpack-runtime.js:33:42)
    at eval (webpack-internal:///(rsc)/./node_modules/@clerk/nextjs/dist/esm/app-router/server/auth.js:7:73)
    at (rsc)/./node_modules/@clerk/nextjs/dist/esm/app-router/server/auth.js (D:\react\next\sse_yt_pag\.next\server\vendor-chunks\@clerk.js:640:1)
    at __webpack_require__ (D:\react\next\sse_yt_pag\.next\server\webpack-runtime.js:33:42)
    at eval (webpack-internal:///(rsc)/./node_modules/@clerk/nextjs/dist/esm/app-router/server/ClerkProvider.js:9:63)
    at (rsc)/./node_modules/@clerk/nextjs/dist/esm/app-router/server/ClerkProvider.js (D:\react\next\sse_yt_pag\.next\server\vendor-chunks\@clerk.js:629:1)
    at __webpack_require__ (D:\react\next\sse_yt_pag\.next\server\webpack-runtime.js:33:42)
    at eval (webpack-internal:///(rsc)/./node_modules/@clerk/nextjs/dist/esm/index.js:58:69)
    at (rsc)/./node_modules/@clerk/nextjs/dist/esm/index.js (D:\react\next\sse_yt_pag\.next\server\vendor-chunks\@clerk.js:896:1)
    at __webpack_require__ (D:\react\next\sse_yt_pag\.next\server\webpack-runtime.js:33:42)
    at eval (webpack-internal:///(rsc)/./app/layout.tsx:12:71)
    at (rsc)/./app/layout.tsx (D:\react\next\sse_yt_pag\.next\server\app\(dashboard)\page.js:655:1)
    at Function.__webpack_require__ (D:\react\next\sse_yt_pag\.next\server\webpack-runtime.js:33:42)
    at runNextTicks (node:internal/process/task_queues:60:5)
    at listOnTimeout (node:internal/timers:540:9)
    at process.processTimers (node:internal/timers:514:7)
    at async eq (D:\react\next\sse_yt_pag\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:402221)
    at async tr (D:\react\next\sse_yt_pag\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:405987)
    at async tn (D:\react\next\sse_yt_pag\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:406537)
    at async tu (D:\react\next\sse_yt_pag\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:36:2057)
    at async D:\react\next\sse_yt_pag\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:36:2564 {
  digest: '1289085325',
  page: '/'
}
```

### Environment

```Shell
System:
OS: Window
```

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Clerk!

[reproduction]: https://clerkdev.notion.site/clerkdev/Creating-a-Minimal-Reproduction-0436afc4203f41aa9aa8700968aaef48

**Comment by sseworld** [comment]
Please tell me the solution

**Comment by sseworld** [comment]
I have resolved the issue by reinstalling the dependency. Thankyou for giving the time on this issue.

**Comment by clerk-cookie** [comment]
This issue has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.
