### ISSUE TITLE
Nextjs 14, docker, production error: Failed to load Clerk

### ISSUE THREAD

**Issue by Mark-Makarov** [clerk/javascript#3185]
### Preliminary Checks

- [X] I have reviewed the documentation: https://clerk.com/docs

- [X] I have searched for existing issues: https://github.com/clerk/javascript/issues

- [X] I have not already reached out to Clerk support via email or Discord (if you have, no need to open an issue here)

- [X] This issue is not a question, general help request, or anything other than a bug report directly related to Clerk. Please ask questions in our Discord community: https://clerk.com/discord.

### Reproduction

https://github.com/Mark-Makarov/Formify

### Publishable key

pk_live_Y2xlcmsuYXN0cm9mbGFyZS5vbmxpbmUk

### Description

Good day.
I have a problem deploying an application to nextjs with clerk.
I'm using docker for deployment.
The problem only appears when deploying production mode on the hosting https://formify.astroflare.online/, here is a screenshot of the error ![im1232age](https://github.com/clerk/javascript/assets/99297990/ed8b58a4-320e-4050-bce9-f19bdf341720) , text:

```
GET https://clerk.astroflare.online/npm/@clerk/clerk-js@4/dist/clerk.browser.js net::ERR_NAME_NOT_RESOLVED
(anonymous) @ 6774-d3be5a9991f8c718.js:2
Q @ 6774-d3be5a9991f8c718.js:2
eo @ 6774-d3be5a9991f8c718.js:2
loadClerkJS @ 6774-d3be5a9991f8c718.js:2
e@6774-d3be5a9991f8c718.js:2
getOrCreateInstance @ 6774-d3be5a9991f8c718.js:2
(anonymous) @ 6774-d3be5a9991f8c718.js:2
useMemo @ fd9d1056-2d18e34f77cecb9b.js:1
t.useMemo @ 7023-76a0887ce31ebb85.js:2
tM @ 6774-d3be5a9991f8c718.js:2
tj @ 6774-d3be5a9991f8c718.js:2
rE@fd9d1056-2d18e34f77cecb9b.js:1
iZ @ fd9d1056-2d18e34f77cecb9b.js:1
ia @ fd9d1056-2d18e34f77cecb9b.js:1
(anonymous) @fd9d1056-2d18e34f77cecb9b.js:1
(anonymous) @fd9d1056-2d18e34f77cecb9b.js:1
oZ @ fd9d1056-2d18e34f77cecb9b.js:1
T @ 7023-76a0887ce31ebb85.js:1
7023-76a0887ce31ebb85.js:1 Error: Clerk: Failed to load Clerk
     at 6774-d3be5a9991f8c718.js:2:5061
     at async e.loadClerkJS (6774-d3be5a9991f8c718.js:2:18718)
```

When you run the application locally, with a production or development key, everything works.
I am ready to provide all the necessary additional data to debug the problem.

### Environment

```Shell
System:
    OS: Linux 5.15 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
    CPU: (48) x64 Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz
    Memory: 59.99 GB / 62.66 GB
    Container: Yes
    Shell: 5.2.15 - /bin/bash
  Binaries:
    Node: 20.12.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.5.0 - /usr/local/bin/npm
  npmPackages:
    @clerk/localizations: ^1.28.2 => 1.28.2 
    @clerk/nextjs: ^4.29.12 => 4.29.12 
    @dnd-kit/core: ^6.1.0 => 6.1.0 
    @hookform/resolvers: ^3.3.4 => 3.3.4 
    @prisma/client: ^5.11.0 => 5.12.1 
    @radix-ui/react-accordion: ^1.1.2 => 1.1.2 
    @radix-ui/react-alert-dialog: ^1.0.5 => 1.0.5 
    @radix-ui/react-aspect-ratio: ^1.0.3 => 1.0.3 
    @radix-ui/react-avatar: ^1.0.4 => 1.0.4 
    @radix-ui/react-checkbox: ^1.0.4 => 1.0.4 
    @radix-ui/react-collapsible: ^1.0.3 => 1.0.3 
    @radix-ui/react-context-menu: ^2.1.5 => 2.1.5 
    @radix-ui/react-dialog: ^1.0.5 => 1.0.5 
    @radix-ui/react-dropdown-menu: ^2.0.6 => 2.0.6 
    @radix-ui/react-hover-card: ^1.0.7 => 1.0.7 
    @radix-ui/react-icons: ^1.3.0 => 1.3.0 
    @radix-ui/react-label: ^2.0.2 => 2.0.2 
    @radix-ui/react-menubar: ^1.0.4 => 1.0.4 
    @radix-ui/react-navigation-menu: ^1.1.4 => 1.1.4 
    @radix-ui/react-popover: ^1.0.7 => 1.0.7 
    @radix-ui/react-progress: ^1.0.3 => 1.0.3 
    @radix-ui/react-radio-group: ^1.1.3 => 1.1.3 
    @radix-ui/react-scroll-area: ^1.0.5 => 1.0.5 
    @radix-ui/react-select: ^2.0.0 => 2.0.0 
    @radix-ui/react-separator: ^1.0.3 => 1.0.3 
    @radix-ui/react-slider: ^1.1.2 => 1.1.2 
    @radix-ui/react-slot: ^1.0.2 => 1.0.2 
    @radix-ui/react-switch: ^1.0.3 => 1.0.3 
    @radix-ui/react-tabs: ^1.0.4 => 1.0.4 
    @radix-ui/react-toast: ^1.1.5 => 1.1.5 
    @radix-ui/react-toggle: ^1.0.3 => 1.0.3 
    @radix-ui/react-toggle-group: ^1.0.4 => 1.0.4 
    @radix-ui/react-tooltip: ^1.0.7 => 1.0.7 
    @types/node: ^20 => 20.12.7 
    @types/react: ^18 => 18.2.76 
    @types/react-dom: ^18 => 18.2.25 
    autoprefixer: ^10.0.1 => 10.4.19 
    class-variance-authority: ^0.7.0 => 0.7.0 
    clsx: ^2.1.0 => 2.1.0 
    cmdk: ^1.0.0 => 1.0.0 
    date-fns: ^3.6.0 => 3.6.0 
    embla-carousel-react: ^8.0.0 => 8.0.2 
    eslint: ^8 => 8.57.0 
    eslint-config-next: 14.1.3 => 14.1.3 
    input-otp: ^1.2.2 => 1.2.4 
    next: 14.2.0 => 14.2.0 
    next-themes: ^0.3.0 => 0.3.0 
    nextjs-toploader: ^1.6.11 => 1.6.11 
    postcss: ^8 => 8.4.38 
    prettier: ^3.2.4 => 3.2.5 
    prettier-plugin-tailwindcss: ^0.5.11 => 0.5.13 
    prisma: ^5.11.0 => 5.12.1 
    react: ^18 => 18.2.0 
    react-confetti: ^6.1.0 => 6.1.0 
    react-day-picker: ^8.10.0 => 8.10.0 
    react-dom: ^18 => 18.2.0 
    react-hook-form: ^7.51.1 => 7.51.2 
    react-icons: ^5.0.1 => 5.0.1 
    react-resizable-panels: ^2.0.13 => 2.0.16 
    sonner: ^1.4.3 => 1.4.41 
    tailwind-merge: ^2.2.2 => 2.2.2 
    tailwindcss: ^3.3.0 => 3.4.3 
    tailwindcss-animate: ^1.0.7 => 1.0.7 
    typescript: ^5 => 5.4.5 
    vaul: ^0.9.0 => 0.9.0 
    zod: ^3.22.4 => 3.22.4
```

**Comment by clerk-cookie** [comment]
This issue has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.
