### ISSUE TITLE
 ReferenceError: Request is not defined

### ISSUE THREAD

**Issue by Imgopz** [clerk/javascript#3970]
### Preliminary Checks

- [X] I have reviewed the documentation: https://clerk.com/docs

- [X] I have searched for existing issues: https://github.com/clerk/javascript/issues

- [X] I have not already reached out to Clerk support via email or Discord (if you have, no need to open an issue here)

- [X] This issue is not a question, general help request, or anything other than a bug report directly related to Clerk. Please ask questions in our Discord community: https://clerk.com/discord.

### Reproduction

NOT

### Publishable key

NO

### Description

ReferenceError: Request is not defined
    at file:///C:/..../backend/node_modules/@clerk/backend/dist/chunk-7MCVPSU7.mjs:1691:20
    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:385:24)
    at async loadESM (node:internal/process/esm_loader:88:5)
    at async handleMainPromise (node:internal/modules/run_main:61:12)

file:///C:/..../backend/node_modules/@clerk/backend/dist/chunk-7MCVPSU7.mjs:1691
var ClerkRequest = class extends Request {
                   ^

ReferenceError: Request is not defined
    at file:///C:/.../node_modules/@clerk/backend/dist/chunk-7MCVPSU7.mjs:1691:20
    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:385:24)
    at async loadESM (node:internal/process/esm_loader:88:5)
    at async handleMainPromise (node:internal/modules/run_main:61:12)

### Environment

```Shell
ReferenceError: Request is not defined
    at file:///C:/..../backend/node_modules/@clerk/backend/dist/chunk-7MCVPSU7.mjs:1691:20
    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:385:24)
    at async loadESM (node:internal/process/esm_loader:88:5)
    at async handleMainPromise (node:internal/modules/run_main:61:12)

file:///C:/.../backend/node_modules/@clerk/backend/dist/chunk-7MCVPSU7.mjs:1691
var ClerkRequest = class extends Request {
                   ^

ReferenceError: Request is not defined
    at file:///C:/.../backend/node_modules/@clerk/backend/dist/chunk-7MCVPSU7.mjs:1691:20
    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:385:24)
    at async loadESM (node:internal/process/esm_loader:88:5)
    at async handleMainPromise (node:internal/modules/run_main:61:12)
```

**Comment by Imgopz** [comment]
I installed node-fetch and imported in the first file and imported Request from node-fetch.

**Comment by anagstef** [comment]
Hello! Thank you for reaching out! We’d love to help you resolve the problem, but we need a bit more information to do so. Could you please provide more details?

- Which of our SDKs are you using?
- What are the steps to reproduce this issue?
- If possible, provide a minimal reproduction repo

**Comment by clerk-cookie** [comment]
Hello 👋

In an effort to keep our GitHub issues clean and focused, we close any issues that are awaiting a reproduction after 8 days on inactivity, and it has been 7 days. This issue will be closed tomorrow unless a reproduction is provided. If it takes longer than this to get a reproduction, that's ok, just drop a comment and we will remove the Stale label.

[How to create a minimal reproduction](https://clerkdev.notion.site/clerkdev/Creating-a-Minimal-Reproduction-0436afc4203f41aa9aa8700968aaef48)

Thanks for being a part of the Clerk community! 🙏

**Comment by clerk-cookie** [comment]
After 8 days without a reproduction being supplied, we are closing this issue. Keep in mind, I'm just a robot, so if I've closed this issue in error, please reply here and my human colleagues will reopen it. Likewise if a reproduction is prepared after it has been closed.

**Comment by clerk-cookie** [comment]
This issue has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.
