### ISSUE TITLE
Error after following RR7 quick start guide - useNavigate() may be used only in the context of a <Router> component

### ISSUE THREAD

**Issue by sanisoclem** [clerk/javascript#4826]
### Preliminary Checks

- [X] I have reviewed the documentation: https://clerk.com/docs

- [X] I have searched for existing issues: https://github.com/clerk/javascript/issues

- [X] I have not already reached out to Clerk support via email or Discord (if you have, no need to open an issue here)

- [X] This issue is not a question, general help request, or anything other than a bug report directly related to Clerk. Please ask questions in our Discord community: https://clerk.com/discord.

### Reproduction

https://github.com/sanisoclem/clerk-rr7-repro

### Publishable key

-

### Description

Starting a new RR7 project and following the clerk guide doesn't produce a working app. The page errors out with: 

> useNavigate() may be used only in the context of a <Router> component.
> 
> Error: useNavigate() may be used only in the context of a <Router> component.
>     at invariant (file:///C:/Users/me/clerk-rr7-repro/node_modules/.pnpm/react-router@7.1.0_react-dom@19.0.0_react@19.0.0__react@19.0.0/node_modules/react-router/dist/development/chunk-W3HZJLUQ.mjs:182:11)
>     at useNavigateUnstable (file:///C:/Users/me/clerk-rr7-repro/node_modules/.pnpm/react-router@7.1.0_react-dom@19.0.0_react@19.0.0__react@19.0.0/node_modules/react-router/dist/development/chunk-W3HZJLUQ.mjs:4118:3)
>     at useNavigate (file:///C:/Users/me/clerk-rr7-repro/node_modules/.pnpm/react-router@7.1.0_react-dom@19.0.0_react@19.0.0__react@19.0.0/node_modules/react-router/dist/development/chunk-W3HZJLUQ.mjs:4115:46)
>     at useAwaitableNavigate (file:///C:/Users/me/clerk-rr7-repro/node_modules/.pnpm/@clerk+react-router@0.1.5_react-dom@19.0.0_react@19.0.0__react-router@7.1.0_react-dom@19.0.0__ctw3iynjxr5uzeptdtabadn6ge/node_modules/@clerk/react-router/src/client/useAwaitableNavigate.tsx:8:20)
>     at ClerkProviderBase (file:///C:/Users/me/clerk-rr7-repro/node_modules/.pnpm/@clerk+react-router@0.1.5_react-dom@19.0.0_react@19.0.0__react-router@7.1.0_react-dom@19.0.0__ctw3iynjxr5uzeptdtabadn6ge/node_modules/@clerk/react-router/src/client/ReactRouterClerkProvider.tsx:36:29)
>     at Object.react-stack-bottom-frame (C:\Users\me\clerk-rr7-repro\node_modules\.pnpm\react-dom@19.0.0_react@19.0.0\node_modules\react-dom\cjs\react-dom-server.node.development.js:8723:18)
>     at renderWithHooks (C:\Users\me\clerk-rr7-repro\node_modules\.pnpm\react-dom@19.0.0_react@19.0.0\node_modules\react-dom\cjs\react-dom-server.node.development.js:46

A few things I have tried:
 - move `ClerkProvider` to layout - same outcome
 - downgrade to react 18 - same outcome

**Steps to reproduce:**

1. `npx create-react-router@latest my-react-router-app`
2. `pnpm add @clerk/react-router`
3. continue following instructions in: https://clerk.com/docs/quickstarts/react-router
    - update `root.tsx` to use `rootAuthLoader()`
    - update `root.tsx`'s default export `App` and wrap `Outlet` with `ClerkProvider`
4. pnpm install
5. pnpm dev

**Expected behavior:**

To be redirected to login page

**Actual behavior:**

Error is shown:

```
Oops!

useNavigate() may be used only in the context of a <Router> component.

Error: useNavigate() may be used only in the context of a <Router> component.
    at invariant (file:///C:/Users/me/clerk-rr7-repro/node_modules/.pnpm/react-router@7.1.0_react-dom@19.0.0_react@19.0.0__react@19.0.0/node_modules/react-router/dist/development/chunk-W3HZJLUQ.mjs:182:11)
    at useNavigateUnstable (file:///C:/Users/me/clerk-rr7-repro/node_modules/.pnpm/react-router@7.1.0_react-dom@19.0.0_react@19.0.0__react@19.0.0/node_modules/react-router/dist/development/chunk-W3HZJLUQ.mjs:4118:3)
    at useNavigate (file:///C:/Users/me/clerk-rr7-repro/node_modules/.pnpm/react-router@7.1.0_react-dom@19.0.0_react@19.0.0__react@19.0.0/node_modules/react-router/dist/development/chunk-W3HZJLUQ.mjs:4115:46)
    at useAwaitableNavigate (file:///C:/Users/me/clerk-rr7-repro/node_modules/.pnpm/@clerk+react-router@0.1.5_react-dom@19.0.0_react@19.0.0__react-router@7.1.0_react-dom@19.0.0__ctw3iynjxr5uzeptdtabadn6ge/node_modules/@clerk/react-router/src/client/useAwaitableNavigate.tsx:8:20)
    at ClerkProviderBase (file:///C:/Users/me/clerk-rr7-repro/node_modules/.pnpm/@clerk+react-router@0.1.5_react-dom@19.0.0_react@19.0.0__react-router@7.1.0_react-dom@19.0.0__ctw3iynjxr5uzeptdtabadn6ge/node_modules/@clerk/react-router/src/client/ReactRouterClerkProvider.tsx:36:29)
    at Object.react-stack-bottom-frame (C:\Users\me\clerk-rr7-repro\node_modules\.pnpm\react-dom@19.0.0_react@19.0.0\node_modules\react-dom\cjs\react-dom-server.node.development.js:8723:18)
    at renderWithHooks (C:\Users\me\clerk-rr7-repro\node_modules\.pnpm\react-dom@19.0.0_react@19.0.0\node_modules\react-dom\cjs\react-dom-server.node.development.js:4621:19)
    at renderElement (C:\Users\me\clerk-rr7-repro\node_modules\.pnpm\react-dom@19.0.0_react@19.0.0\node_modules\react-dom\cjs\react-dom-server.node.development.js:5056:23)
    at retryNode (C:\Users\me\clerk-rr7-repro\node_modules\.pnpm\react-dom@19.0.0_react@19.0.0\node_modules\react-dom\cjs\react-dom-server.node.development.js:5704:22)
    at renderNodeDestructive (C:\Users\me\clerk-rr7-repro\node_modules\.pnpm\react-dom@19.0.0_react@19.0.0\node_modules\react-dom\cjs\react-dom-server.node.development.js:5530:11)
```

### Environment

```Shell
System:
    OS: Windows 11 10.0.26100
    CPU: (32) x64 AMD Ryzen 9 7950X3D 16-Core Processor
    Memory: 36.24 GB / 63.14 GB
  Binaries:
    Node: 22.12.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.9.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.15.0 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.26100.1882
  npmPackages:
    @clerk/react-router: ^0.1.5 => 0.1.5
    @react-router/dev: ^7.1.0 => 7.1.0
    @react-router/node: ^7.1.0 => 7.1.0
    @react-router/serve: ^7.1.0 => 7.1.0
    @types/node: ^20 => 20.17.10
    @types/react: ^19.0.1 => 19.0.2
    @types/react-dom: ^19.0.1 => 19.0.2
    autoprefixer: ^10.4.20 => 10.4.20
    cross-env: ^7.0.3 => 7.0.3
    isbot: ^5.1.17 => 5.1.18
    postcss: ^8.4.49 => 8.4.49
    react: ^19.0.0 => 19.0.0
    react-dom: ^19.0.0 => 19.0.0
    react-router: ^7.1.0 => 7.1.0
    tailwindcss: ^3.4.16 => 3.4.17
    typescript: ^5.7.2 => 5.7.2
    vite: ^5.4.11 => 5.4.11
    vite-tsconfig-paths: ^5.1.4 => 5.1.4
```

**Comment by AdiRishi** [comment]
I was just migrating my repo to rr7 and `@clerk/react-router` and ran into this as well, would appreciate a solution :)

Happy to provide more information / reproductions if necessary.

**Comment by dburdan** [comment]
See here: https://github.com/clerk/javascript/issues/4641#issuecomment-2524696977

Temporarily downgrading Vite from v6 to v5 also worked for me.

**Comment by timothyclifford-loambio** [comment]
We had the same issue, downgrading Node from 22.12 to 22.11 seemed to resolve.

**Comment by simonjodet** [comment]
> We had the same issue, downgrading Node from 22.12 to 22.11 seemed to resolve.

I downgraded to node v20.18.1 using nvm and it fixed the issue.

**Comment by sanisoclem** [comment]
> See here: [#4641 (comment)](https://github.com/clerk/javascript/issues/4641#issuecomment-2524696977)
> 
> Temporarily downgrading Vite from v6 to v5 also worked for me.

the repro is using `vite: ^5.4.11`


> We had the same issue, downgrading Node from 22.12 to 22.11 seemed to resolve.

Thanks, this also worked for the app I am migrating.

Had an issue with the [minimal repro](https://github.com/sanisoclem/clerk-rr7-repro) though - the example given in step 4 of the guide says: 

> `<SignInButton />`: An unstyled component that links to the sign-in page. In this example, since no props or [environment variables](https://clerk.com/docs/deployments/clerk-environment-variables) are set for the sign-in URL, this component links to the [Account Portal sign-in page](https://clerk.com/docs/customization/account-portal/overview#sign-in).

when clicking on the sign in button, it doesn't redirect to the account portal hosted signin page. Instead it gets redirected to: `/signin` which does not exist. 

To make it work, had to create the `/signin` route:

```ts
import { SignIn } from '@clerk/react-router';

export default function SignInPage() {
  return (
    <div
      style={{
        backgroundImage: 'url(/bg.svg)',
        backgroundPosition: 'center',
        backgroundSize: 'cover'
      }}
      className="flex h-screen w-screen items-center justify-center"
    >
      <SignIn routing="path" path="/signin" />
    </div>
  );
}
```

and update `routes.ts`

```ts
import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  index("routes/home.tsx"),
  route("signin", "routes/signin.tsx"),
] satisfies RouteConfig;
```

**Comment by wobsoriano** [comment]
Hey folks - react-router released 7.1.2 which includes a fix for this issue!

https://github.com/remix-run/react-router/blob/main/CHANGELOG.md#v712
